name: 制作镜像并推送到私有仓库

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
      - name: 制作镜像并推送到私有仓库
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-beijing.aliyuncs.com
          docker build -t registry.cn-beijing.aliyuncs.com/marbleqi/openai .
          docker push registry.cn-beijing.aliyuncs.com/marbleqi/openai
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
